
import 'package:html_editor_enhanced/src/model/transfer_method.dart';

enum DefaultTransferMethod {
  onBeforeCommand,
  onChangeContent,
  onChangeCodeView,
  onDialogShown,
  onEnter,
  onFocus,
  onBlur,
  onBlurCodeView,
  onImageLinkInsert,
  onImageUpload,
  onImageUploadError,
  onKeyDown,
  onKeyUp,
  onMouseDown,
  onMouseUp,
  onPaste,
  onScroll,
  characterCount,
  onTextFontSizeChanged,
  onDragEnter,
  onDragLeave,
  onSelectMention,
  getText,
  getTextWithSignatureContent,
  getHeight,
  isFullScreen,
  isActivatedCodeView,
  getSelectedText,
  getSelectedTextHtml,
  updateToolbar,
  onIframeLoaded,
  insertSignature,
  removeSignature,
  updateBodyDirection,
  setDimensionDropZone,
  setInputType,
  setText,
  setFullScreen,
  setFocus,
  clear,
  setHint,
  toggleCodeView,
  disable,
  enable,
  undo,
  redo,
  insertText,
  insertHtml,
  insertNetworkImage,
  insertLink,
  reload,
  addNotification,
  removeNotification,
  execCommand,
  execSummernoteAPI,
  setFontSize,
  changeListStyle,
  changeLineHeight,
  changeTextDirection,
  changeCase,
  insertTable,
  onDragDropEvent,
  unknown;

  TransferMethod get method => TransferMethod(name);
}

